version: "2.4"

services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_DB=northwind
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql_bin:/usr/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
      - ./northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
      - ./files:/files
    ports:
      - "55432:5432"
    networks:
      - weave

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - postgresql_bin:/usr/lib/postgresql
      - pgadmin_root_prefs:/root/.pgadmin
      - pgadmin_working_dir:/var/lib/pgadmin
      - ./files:/files
    ports:
      - "5050:5050"
    networks:
      - weave

  weavescope:
    container_name: weavescope
    image: weaveworks/scope:latest
    # Weave Scope needs privileged mode, host PID, and host networking
    privileged: true
    pid: "host"
    network_mode: "host"
    environment:
      - WEAVE_EXEC=/usr/local/bin/weave
    volumes:
      # Required so Scope can see Docker events and container info
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["scope", "launch"]

networks:
  weave:
    external: true # Remove or set to 'false' if you want Compose to create its own network

volumes:
  pgadmin_root_prefs:
    driver: local
  pgadmin_working_dir:
    driver: local
  postgresql_data:
    driver: local
  postgresql_bin:
    driver: local
